# strategies/__init__.py

from .moving_average_crossover import moving_average_crossover,execute_moving_average_crossover_strategy
from .rsi_strategy import rsi_strategy,execute_rsi_strategy
from .bollinger_bands import bollinger_bands,execute_bollinger_bands_strategy
from .ml_strategy import ml_strategy
from .macd_strategy import macd_strategy,execute_macd_strategy
from .ichimoku_cloud_strategy import ichimoku_cloud_strategy
from .stochastic_oscillator_strategy import stochastic_oscillator_strategy